#!/usr/bin/luajit

require("src.amenities.init")
log.level = "error"

local default = require("src.configuration.section.default")

local default_str = inspect(default:default())

local fmt = [[
-- This file was autogenerated by sh/get_default_config.lua! if you ever want to 
-- reset your configuration to default, simply run:
--
-- $ sh/get_default_config.lua > config/awesome.lua
--
-- Happy hacking!

local config = %s

return config
]]

print(string.format(fmt, default_str))