#!/bin/sh

lua lib/bundler/init.lua -i lib/bundler -o build/bundler \
    -e init.lua \
    -e Bundler.lua \
    -p lib/bundler/public \
    -l "gears.filesystem" \
    -l "<UUID>.src.<OUT_FILE>" \
    -l "<UUID>.Bundler"