# TODO https://github.com/actions/cache

name: Build
run-name: Build on push - ${{ github.actor }}
on: [push]
jobs:
  Build-Appmenu:
    runs-on: ubuntu-latest
    steps: 
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Set up environment
        uses: ./.github/actions/setup
      - name: Get changed files in the appmenu folder
        id: changed-files-appmenu
        uses: tj-actions/changed-files@v36
        with:
          files: src/appmenu/**
      - name: Running bundler
        if: steps.changed-files-appmenu.outputs.any_changed == 'true'
        run: sh src/appmenu/bundle
      - name: Push to Appmenu repository
        if: steps.changed-files-appmenu.outputs.any_changed == 'true'
        uses: cpina/github-action-push-to-another-repository@main
        env:
          SSH_DEPLOY_KEY: ${{ secrets.APPMENU_DEPLOY_KEY }}
        with:
          source-directory: 'build/appmenu'
          destination-github-username: 'oezingle'
          destination-repository-name: 'Awesome-Appmenu'  
          user-email: oezingle@gmail.com
          target-branch: master
  Build-Bundler:
    runs-on: ubuntu-latest
    steps: 
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Set up environment
        uses: ./.github/actions/setup
      - name: Get changed files in the bundler folder
        id: changed-files-bundler
        uses: tj-actions/changed-files@v36
        with:
          files: lib/bundler/**
      - name: Running bundler
        if: steps.changed-files-bundler.outputs.any_changed == 'true'
        run: sh lib/bundler/bootstrap
      - name: Push to bundler repository
        if: steps.changed-files-bundler.outputs.any_changed == 'true'
        uses: cpina/github-action-push-to-another-repository@main
        env:
          SSH_DEPLOY_KEY: ${{ secrets.BUNDLER_DEPLOY_KEY }}
        with:
          source-directory: 'build/bundler'
          destination-github-username: 'oezingle'
          destination-repository-name: 'lua-bundler'
          user-email: oezingle@gmail.com
          target-branch: master