name: Setup
run-name: Setup lua environment
on: [workflow_call]
jobs:
  Setup:
    runs-on: ubuntu-latest
    steps:
      - name: Change dir
        run: cd ${{ github.workspace }}
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: copy default config
        run: cp config_example.lua config.lua
      - name: copy example wallpaper
        run: |
          mkdir -p ~/Pictures
          wget https://upload.wikimedia.org/wikipedia/commons/thumb/3/3a/Cat03.jpg/1025px-Cat03.jpg -O ~/Pictures/wallpaper.jpg
      - uses: ilammy/msvc-dev-cmd@v1 # Windows fix for lua
      - name: Building lua
        uses: leafo/gh-actions-lua@v10 # Builds lua from source - not fast, but should work
        with:
          luaVersion: "5.3.5"
      - name: Install LGI dependency
        run: sudo apt-get install -y libgirepository1.0-dev
      - name: Building Luarocks
        uses: leafo/gh-actions-luarocks@v4
      - name: Installing lgi
        run: luarocks install lgi