name: Test
run-name: Run tests - ${{ github.actor }}
on: [push]
jobs:
  Tests-lua:
    runs-on: ubuntu-latest
    steps: 
      - name: Change dir
        run: cd ${{ github.workspace }}
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: "Cloning submodules"
        run: git submodule update --init --recursive
      - name: Install awesome
        run: sudo apt-get install -y awesome awesome-extra
      - name: Run tests
        run: lua test.lua
        #with: 
        #  luaVersion: "luajit-2.1.0-beta3"
