# TODO https://github.com/actions/cache

name: Test
run-name: Unit tests - ${{ github.actor }}
on: [push]
jobs:
  Test-Lua-5_3:
    runs-on: ubuntu-latest
    steps: 
      - name: Set up environment
        uses: .github/workflows/setup.yml
      - run: lua test.lua